rgb_front:
  id: rgb_front
  type: sensor.camera.rgb
  x: 1.5
  y: 0.0
  z: 2.5
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
  width: 1600
  height: 900
  fov: 150
rgb_left:
  id: rgb_left
  type: sensor.camera.rgb
  x: 0
  y: -0.3
  z: 2.5
  roll: 0.0
  pitch: 0.0
  yaw: -90.0
  width: 1600
  height: 900
  fov: 150
rgb_right:
  id: rgb_right
  type: sensor.camera.rgb
  x: 0
  y: 0.3
  z: 2.5
  roll: 0.0
  pitch: 0.0
  yaw: 90.0
  width: 1600
  height: 900
  fov: 150
rgb_back:
  id: rgb_back
  type: sensor.camera.rgb
  x: -1.6
  y: 0.0
  z: 2.5
  roll: 0.0
  pitch: 0.0
  yaw: 180.0
  width: 1600
  height: 900
  fov: 150
seg_front:
  id: seg_front
  type: sensor.camera.semantic_segmentation
  x: 1.3
  y: 0.0
  z: 2.5
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
  width: 1600
  height: 900
  fov: 150
seg_left:
  id: seg_left
  type: sensor.camera.semantic_segmentation
  x: 0
  y: -0.3
  z: 2.5
  roll: 0.0
  pitch: 0.0
  yaw: -90.0
  width: 1600
  height: 900
  fov: 150
seg_right:
  id: seg_right
  type: sensor.camera.semantic_segmentation
  x: 0
  y: 0.3
  z: 2.5
  roll: 0.0
  pitch: 0.0
  yaw: 90.0
  width: 1600
  height: 900
  fov: 150
seg_back:
  id: seg_back
  type: sensor.camera.semantic_segmentation
  x: -1.6
  y: 0.0
  z: 2.5
  roll: 0.0
  pitch: 0.0
  yaw: 180.0
  width: 1600
  height: 900
  fov: 150
depth_front:
  id: depth_front
  type: sensor.camera.depth
  x: 1.3
  y: 0.0
  z: 2.5
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
  width: 1600
  height: 900
  fov: 150
depth_left:
  id: depth_left
  type: sensor.camera.depth
  x: 0
  y: -0.3
  z: 2.5
  roll: 0.0
  pitch: 0.0
  yaw: -90.0
  width: 1600
  height: 900
  fov: 150
depth_right:
  id: depth_right
  type: sensor.camera.depth
  x: 0
  y: 0.3
  z: 2.5
  roll: 0.0
  pitch: 0.0
  yaw: 90.0
  width: 1600
  height: 900
  fov: 150
depth_back:
  id: depth_back
  type: sensor.camera.depth
  x: -1.6
  y: 0.0
  z: 2.5
  roll: 0.0
  pitch: 0.0
  yaw: 180.0
  width: 1600
  height: 900
  fov: 150
lidar:
  id: lidar
  type: sensor.lidar.ray_cast
  x: 0.0
  y: 0.0
  z: 2.5
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
imu:
  id: imu
  type: sensor.other.imu
  x: 0.0
  y: 0.0
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
  sensor_tick: 0.05
gps:
  id: gps
  type: sensor.other.gnss
  x: 0.0
  y: 0.0
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
  sensor_tick: 0.01
speed:
  id: speed
  type: sensor.speedometer
  reading_frequency: 20
